version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_DOMAIN_URL=${NEXT_PUBLIC_DOMAIN_URL}
      - NEXT_PUBLIC_SECURE_TOKEN=${NEXT_PUBLIC_SECURE_TOKEN}
      - NEXT_PUBLIC_LOCALE=${NEXT_PUBLIC_LOCALE}
      - NEXT_PUBLIC_ADDITIONAL_LANG=${NEXT_PUBLIC_ADDITIONAL_LANG}
      - NEXT_PUBLIC_HOTJAR_ID=${NEXT_PUBLIC_HOTJAR_ID}
